import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Link from "next/link";
import Socials from "../components/Socials";
import WorkCard from "../components/WorkCard";
import workData from "../public/workData.json";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Pratham Sharma</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<meta
					name="keywords"
					content="Pratham Sharma Frontend Developer React Reactjs Nextjs Freelancer"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className=" dark:bg-black bg-white text-slate-800 dark:text-zinc-50 px-10 md:px-56 flex flex-col gap-10 items-center md:items-start antialiased selection:bg-blue-200 ">
				{/* About */}
				<div className="flex flex-col gap-10 w-fit md:min-h-[80vh] justify-center tracking-wide mt-36 mx-2 md:m-10 md:mb-0 mr-5">
					<div className="flex flex-col md:gap-10">
						<h1
							className="text-5xl md:text-[5rem]"
							style={{ fontFamily: "'Old Standard TT', serif" }}
						>
							Hello! I&apos;m Pratham.
						</h1>
						<h1
							className="text-5xl md:text-[4.5rem] italic"
							style={{ fontFamily: "'Old Standard TT', serif" }}
						>
							Frontend Developer
						</h1>
					</div>
					<div className="flex flex-row-reverse">
						<p className="text-2xl md:w-1/2">
							I'm a Frontend Developer based working from Delhi. Started
							learning web development when i was 14, ever since then I'm
							building interfaces with state of art, scalable technologies and .
						</p>
					</div>
				</div>
				{/* <div className="">
						<img src="img1.jpg" className=""></img>
					</div> */}
				{/* Projects */}
				<div className="flex flex-col gap-10 pb-5 w-full">
					<div className="flex w-full items-center gap-10">
						<h2 className=" text-3xl font-bold text-center md:text-left">
							Projects
						</h2>
						<div className="hidden md:block bg-blue-400/80 h-[1px] w-full"></div>
					</div>
					<div className="flex md:flex-wrap flex-col md:flex-row gap-4 justify-center md:justify-start items-stretch">
						{workData.map((item, iter) => {
							return (
								<WorkCard
									title={item.title}
									desc={item.desc}
									link={item.link}
									skills={item.tech}
								/>
							);
						})}
					</div>
				</div>
				{/* Footer */}
				<Footer />
			</main>
		</>
	);
}
